env:
  browser: true
  node: true
  es6: true
extends:
  - airbnb-base
  - "plugin:jest/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
plugins:
  - jest