version: 2
jobs:
  prebuild:
    docker:
      - image: node:12

    dependencies:
      pre:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

    steps:
      - checkout
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: node:12

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npx semantic-release

  lint:
    docker:
      - image: node:12

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm run lint

  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm run test

  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm run build

workflows:
  version: 2
  build_deploy:
    jobs:
      - prebuild:
          context: carimflex-publish-semantic-release
      - lint:
          requires:
            - prebuild
      - test:
          requires:
            - prebuild

      - build:
          context: carimflex-publish-semantic-release
          requires:
            - lint
            - test
      - deploy:
          context: carimflex-publish-semantic-release
          requires:
            - build
          filters:
            branches:
              only: master
      
